### ISSUE TITLE
As a user I want to edit and delete books from my list so I can manage my books better

### ISSUE THREAD

**Issue by wiktoria75** [wiktoria75/react-and-spring#4]
## Tasks:
- [ ] Create "read books" view 
- [ ] Create button for marking book as read
- [ ] Create endpoint responsible for marking book as 'read'
