### ISSUE TITLE
As an admin I want to see list of all users and number of books they've read so I can see their progress

### ISSUE THREAD

**Issue by wiktoria75** [wiktoria75/react-and-spring#6]
## Tasks:
- [x] Create view for list of all students for admin page
- [x] Add POST method to collect all students
- [x] Create corresponding endpoint in backend

**Comment by wiktoria75** [comment]
Of course! Here's a draft for the pull request:

---

# Frontend Changes:
- Implemented a view to display a list of all students on the admin page.
- Added the count of finished books to each student's information.
- Added a POST method to collect all students' data.

# Backend Changes:
- Created a corresponding endpoint in the backend to serve student data.

This pull request enhances the admin page by allowing administrators to view all students and the count of their finished books.

**Comment by wiktoria75** [comment]
# Frontend Changes:
- Implemented a view to display a list of all students on the admin page.
- Added the count of finished books to each student's information.
- Added a POST method to collect all students' data.

# Backend Changes:
- Created a corresponding endpoint in the backend to serve student data.

This pull request enhances the admin page by allowing administrators to view all students and the count of their finished books.
