### ISSUE TITLE
Initial Project Setup

### ISSUE THREAD

**Issue by wiktoria75** [wiktoria75/react-and-spring#8]
## Tasks:
- [x] set up spring project
- [x] set up react project
- [ ] set up database (H2)
